# Generated by Django 4.2.23 on 2025-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="capture",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
