# Generated by Django 4.2.23 on 2025-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captures", "0002_capture_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capture",
            name="website_url",
            field=models.URLField(max_length=5000),
        ),
    ]
