# Generated by Django 4.2.23 on 2025-08-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
