# Generated by Django 4.2.23 on 2025-08-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="free_capture_limit",
            field=models.PositiveIntegerField(
                default=10, help_text="Number of free captures allowed for this user"
            ),
        ),
    ]
