# Generated by Django 4.2.23 on 2025-08-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_free_capture_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="customuser",
            name="stripe_subscription_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe price ID for the user's subscription",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("past_due", "Past Due"),
                    ("trialing", "Trialing"),
                    ("unpaid", "Unpaid"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
