# Generated by Django 4.2.23 on 2025-08-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_customuser_stripe_subscription_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="activated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the subscription was activated", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the subscription was canceled", null=True
            ),
        ),
    ]
