# Generated by Django 4.2.23 on 2025-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_subscription_activated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="free_capture_limit",
            field=models.PositiveIntegerField(
                default=5, help_text="Number of free captures allowed for this user"
            ),
        ),
    ]
