# Generated by Django 4.2.23 on 2025-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_free_capture_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Source that brought the user to the platform",
                max_length=100,
                null=True,
            ),
        ),
    ]
