# Generated by Django 4.2.23 on 2025-10-25 07:57

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="free_capture_limit",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="google_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="stripe_customer_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="source",
            field=models.CharField(
                blank=True,
                default="google",
                help_text="How the user found out about the service (e.g., 'google', 'twitter', 'friend')",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="user",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="custom_user",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
